### PR TITLE
feat(props): allow to enable/disable the input field and tags via a prop (editable)

### PR DESCRIPTION
**Pull request by gianpaj**
Useful when submitting a form we want to freeze the interface until completed

### CODE REVIEW

**Review by Ashoat — CHANGES_REQUESTED** [review]
Thanks for the PR, this makes sense to me! Sorry it took so long to get back.

Only one request: can you add your new prop to the `README.md`?

**Comment by gianpaj** [comment]
no worries. here you go

**Comment by Ashoat** [comment]
Released `react-native-tag-input@0.0.19` with this PR. Thanks @gianpaj!

**Comment by gianpaj** [comment]
no worries. thanks for creating this great package 😀

**Pull request merged**
