### PR TITLE
Allow custom input renderer

### PR DESCRIPTION
**Pull request by ThiagoNP**
This PR makes possible to render elements for the input. An use case to this feature would be rendering an auto complete input instead of the default text input.

### CODE REVIEW

**Comment by sibelius** [comment]
could u please rebase and fix conflicts?

**Comment by ThiagoNP** [comment]
@sibelius Fixed 😄

**Comment by sibelius** [comment]
I'm gonna need a little bit of more time to test it

**Comment by sibelius** [comment]
@jwohlfert23 please review this as well

**Comment by binzailani3136** [comment]
Hi everyone!
It's very interesting PR and I've reviewed it too.
But I can't find the `auto-complete-library` and where can I pull `auto-complete-library`?

**Pull request closed without merging**
